# The URL of the site
baseURL = 'https://relaycomputer.co.uk/'

# The title of site
languageCode = 'en-gb'
title = 'Relay Computer'

# Disable Hugo generator meta tag in the HTML head.
disableHugoGeneratorInject =  true

enableRobotsTXT = true
paginate = 12

[permalinks]
  posts = '/posts/:year/:month/:slug'

[services]
  [services.googleAnalytics]
    id = 'G-RNXVW69CMT'

[params]
  author = 'Paul Law'
  description = 'My journey in constructing an 8 bit relay computer from scratch … made from of a ton of solder, wires, lights, relays, sweat, tears, swearing and money.'
  youtube_channel_url = 'https://www.youtube.com/channel/UCDn07eKw2HDPIgSAGQgliAA'
  github_profile_url = 'https://github.com/paul80nd'
  editor_url = 'https://editor.relaycomputer.co.uk'
  simulator_url = 'https://simulator.relaycomputer.co.uk'

# Allow html in markdown (typically <br> and the like)
[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = 'monokailight'

[taxonomies]
    card = 'cards'
    tag = 'tags'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Overview'
  url = '/pages/overview/'
  weight = 2

[[menu.main]]
  name = 'Progress'
  url = '/pages/progress/'
  weight = 3

[[menu.main]]
  name = 'Cards'
  url = '/cards/'
  weight = 4

[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 5

[[menu.main]]
  name = 'Tags'
  url = '/tags/'
  weight = 6
